apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://example.com/logo.jpeg
  children: [infrastructure]
